default: &default
  adapter: postgresql
  encoding: unicode
  database: fc_rails_development
  username: fc_rails_user
  password: p000123
  host: localhost
  template: template0

development:
  <<: *default
  database: fc_rails_development

test:
  <<: *default
  database: fc_rails_test

production:
  <<: *default
  database: fc_rails_production
